require_relative 'application/application_command'
require_relative 'cli/cli_command'
require_relative 'console/console_command'
require_relative 'generate/generate_command'
require_relative 'destroy/destroy_command'
require_relative 'help/help'
